### ISSUE TITLE
Bug:Page Navigation not working in Advanced Solidity Level

### ISSUE THREAD

**Issue by SahilAujla** [LearnWeb3DAO/Sophomore-Track#1]
In the advanced solidity level, when we click on the links of individual topics, Like "Structs", it changes the URL in the search bar and add #structs at the end of the URL but does not really take us to that part. 

Maybe the developer forgot to add ID's to the different sections of the page. 

![image](https://user-images.githubusercontent.com/83442423/157035459-a8d72b90-7f52-4038-afe9-827c60278e95.png)

**Comment by Arun9650** [comment]
it works in md file

**Comment by yanukadeneth99** [comment]
Checked this, and seems like it's fixed now 😄
