### ISSUE TITLE
Suggestion: Make the sidebar fixed while scrolling the page.

### ISSUE THREAD

**Issue by SahilAujla** [LearnWeb3DAO/Sophomore-Track#2]
It would be more user friendly if the sidebar containing "Dashboard" and "Level" options just stays fixed at its position when scrolling the page.

**Comment by vaib1343** [comment]
Hey I can work on this issue, please assign it to me.

**Comment by yanukadeneth99** [comment]
Since the website will go through a Revamp, this issue might get solved in the new version.
