### ISSUE TITLE
Content Missing : Sophomore Track - Mixed Topics

### ISSUE THREAD

**Issue by gGh00sTt** [LearnWeb3DAO/Sophomore-Track#4]
The sophomore track , Mixed Topics has missed the topic "React Hooks" which is included in its table of contents. https://www.learnweb3.io/tracks/sophomore/mixed-topics#react-hooks

**Comment by taylorferran** [comment]
I've created a PR here https://github.com/LearnWeb3DAO/Sophomore-Mixed-Topics/pull/8

**Comment by yanukadeneth99** [comment]
Looks like this is fixed.
