### ISSUE TITLE
Add 'await' (UI jumping)

### ISSUE THREAD

**Issue by happylolonly** [LearnWeb3DAO/Sophomore-Track#63]
In https://github.com/LearnWeb3DAO/Sophomore-Track/blob/main/NFT-Collection.md on this line
`const _presaleStarted = checkIfPresaleStarted();`
should be `await` (seems like UI jumping because of this).

Good small issue, for someone who can do some refactoring.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/18665326/217042032-3e8da979-efaf-47bf-b272-4830a560c816.png">

**Comment by ljcutts** [comment]
@happylolonly I'll look into this and see if it's a real issue. Thank you

**Comment by yanukadeneth99** [comment]
@happylolonly I don't think you can add the await keyword there since `useEffect` isn't an async function. 

If that does have a significant effect, maybe you can move all of that into an async function which manages them and then call that on `useEffect()`

**Comment by happylolonly** [comment]
> @happylolonly I don't think you can add the `await` keyword there since `useEffect` isn't an async function.
> 
> If that does have a significant effect, maybe you can move all of that into an async function which manages them and then call that on `useEffect()`

yes, then need some refactoring 😄

**Comment by ljcutts** [comment]
@happylolonly any update on this?

**Comment by happylolonly** [comment]
@ljcutts , No, I no working on this, only suggested, good first issue for someone.

**Comment by yanukadeneth99** [comment]
Thanks. Closing this issue since there is no work to be done in this.
