### ISSUE TITLE
"https://nft-collection-sneh1999.vercel.app/api/" coming back invalid

### ISSUE THREAD

**Issue by mlewis2257** [LearnWeb3DAO/Sophomore-Track#78]
For the METADATA_URL the address is invalid and isn't working. Every time I go to deploy the contract I get back an 'INVALID ARGUMENT ERROR'. Also when I go to click on the website it doesn't work and I get a 404 page not found error.

`// Address of the deployed contract address
const WHITELIST_CONTRACT_ADDRESS = "0x30084B5d1fee035703Ba2Ea6e60B4B1DB91b4880";
// URL to extract Metadata for a Crypto Dev NFT
const METADATA_URL = "https://nft-collection-sneh1999.vercel.app/api/";

module.exports = {
  WHITELIST_CONTRACT_ADDRESS,
  METADATA_URL,
};`

**Comment by yanukadeneth99** [comment]
Hey @mlewis2257, thanks for raising this. 

Will push this to the team. 

@ljcutts @haardikk21

**Comment by haardikk21** [comment]
You shouldn't be using that Metadata URL. You are supposed to replace `METADATA_URL` with your Vercel app's URL. Closing this issue, reach out in Discord for further help.

**Comment by yanukadeneth99** [comment]
@mlewis2257  If you haven't already, this is the link to join the discord server : http://discord.gg/learnweb3
