### ISSUE TITLE
NFT Collection: update push-to-GitHub instructions

### ISSUE THREAD

**Issue by Coding-with-Adam** [LearnWeb3DAO/Sophomore-Track#82]
Hi, I am running through the NFT Collection tutorial and realized that the below instruction (inside the NFT-Collection.md file) is not possible in Vercel, which means I (and others students) are likely to get stuck.

- Click Edit next to Root Directory and set it to my-app

The problem lies in the previous step where we push the whole NFT-Collection folder to github. For some reason, somewhere along the tutorial, the `my-app` folder has git initialized inside of it. As a result, when pushing the NFT Collection folder, it pushes my-app to GitHub as a submodule. Consequently, in Vercel, onc cannot set `my-app` to the Root Directly of Vercel. 

I solved this by deleting the .git file inside my-app and repushed the whole NFT-Collection (which pushed my-app as a folder instead of a submodule).

But I'm not sure this is the best solution. Can you please guide me by letting me know what the best solution would be. 

I'd be happy to create a PR and update your tutorial/NFT-Collection.md file once I know the best way to move forward. 

Thank you,
adam

**Comment by ljcutts** [comment]
Hello, this is an issue we actually try to address like here 
https://learnweb3.io/courses/2204ab10-6a7b-44ec-9705-1a6682a4725f/lessons/6265bd13-4757-4f29-8412-08728844067f
If you want, you can submit PRs for the other tutorials that will run into this issue.

**Comment by yanukadeneth99** [comment]
I believe this is already answered by LJ.

Closing this issue out. Feel free to reach out to us if you have further issues.

**Comment by Coding-with-Adam** [comment]
> Hello, this is an issue we actually try to address like here https://learnweb3.io/courses/2204ab10-6a7b-44ec-9705-1a6682a4725f/lessons/6265bd13-4757-4f29-8412-08728844067f If you want, you can submit PRs for the other tutorials that will run into this issue.

HI @ljcutts I [created the PR](https://github.com/LearnWeb3DAO/Sophomore-Track/pull/85) for this issue in the whitelist-dapp lesson.

**Comment by yanukadeneth99** [comment]
Thanks @Coding-with-Adam, will check that out.
